# This is how a user sets up their own pipeline while inheriting your Platform's CI/CD standards!

trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MLOpsPlatform
      type: git
      name: RapidMLOps
      ref: refs/heads/main

variables:
  - name: environment
    value: 'dev'
  - name: agentPool
    value: 'ubuntu-latest'

stages:
  - stage: BuildDataAsset
    displayName: "Create Fraud Data Assets"
    jobs:
      - template: cicd/azure-devops/azureml/jobs/data-asset-job.yaml@MLOpsPlatform
        parameters:
          environment: $(environment)
          agentPool: $(agentPool)
          requirementsFile: 'requirements.txt'
          subscriptionId: $(SUBSCRIPTION_ID)
          resourceGroup: $(RESOURCE_GROUP)
          workspaceName: $(WORKSPACE_NAME)
          
          commitSha: $(Build.SourceVersion)
          prId: $(System.PullRequest.PullRequestId)
          sourceBranch: $(Build.SourceBranchName)
