trigger:
  branches:
    include:
      - main
      - dev
  paths:
    include:
      - data_asset/*

variables:
  # Using mock variables for the example pipeline execution
  - name: environment
    value: 'dev'
  - name: agentPool
    value: 'ubuntu-latest'
  - name: requirementsFile
    value: 'requirements_azureml.txt'
  - name: subscriptionId
    value: 'mock-sub-123'
  - name: resourceGroup
    value: 'mock-rg-dev'
  - name: workspaceName
    value: 'mock-workspace-dev'

stages:
  - stage: BuildAndCreateDataAsset
    displayName: "Build and Create Data Asset Stage"
    jobs:
      - template: ../jobs/data-asset-job.yaml
        parameters:
          environment: $(environment)
          agentPool: $(agentPool)
          requirementsFile: $(requirementsFile)
          subscriptionId: $(subscriptionId)
          resourceGroup: $(resourceGroup)
          workspaceName: $(workspaceName)
          
          # Native Azure DevOps Lineage Variables!
          commitSha: $(Build.SourceVersion)
          prId: $(System.PullRequest.PullRequestId)
          sourceBranch: $(Build.SourceBranchName)
