trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MLOpsPlatform
      type: git
      name: RapidMLOps
      ref: refs/tags/v1.0.0

variables:
  - template: ../variables/common.yaml
  - template: ../variables/stg.yaml

extends:
  template: cicd/azure-devops/azureml/templates/e2e-mlops-pipeline-template.yaml@MLOpsPlatform
  parameters:
    agentPool: $(agentPool)
