parameters:
  - name: environment
    type: string
  - name: commitSha
    type: string
    default: ''
  - name: prId
    type: string
    default: ''
  - name: sourceBranch
    type: string
    default: ''
  - name: environmentFolder
    type: string
    default: 'environments'
  - name: environmentConfigFile
    type: string
    default: 'environment.yaml'


steps:
  - script: |
      echo "Executing Dynamic Git Diff for Environments..."
      
      # Build the args
      CMD_ARGS="--environment ${{ parameters.environment }}"
      
      if [ -n "${{ parameters.commitSha }}" ]; then
        CMD_ARGS="$CMD_ARGS --commit_sha ${{ parameters.commitSha }}"
      fi
      if [ -n "${{ parameters.prId }}" ]; then
        CMD_ARGS="$CMD_ARGS --pr_id ${{ parameters.prId }}"
      fi
      if [ -n "${{ parameters.sourceBranch }}" ]; then
        CMD_ARGS="$CMD_ARGS --source_branch ${{ parameters.sourceBranch }}"
      fi
      if [ -n "${{ parameters.environmentFolder }}" ]; then
        CMD_ARGS="$CMD_ARGS --environment_folder ${{ parameters.environmentFolder }}"
      fi
      if [ -n "${{ parameters.environmentConfigFile }}" ]; then
        CMD_ARGS="$CMD_ARGS --environment_config_file ${{ parameters.environmentConfigFile }}"
      fi
      
      # The python code executes exactly where the multi-checkout logic placed the rapidmlops template code!
      python $(Pipeline.Workspace)/s/rapidmlops/src/rapidmlops/azureml/environment/handler.py $CMD_ARGS
    displayName: 'Execute handler.py Git Orchestrator'